"""sync current database models

Revision ID: 007b4e6be146
Revises: 9c4e7b2a1d65
Create Date: 2026-09-01 16:49:17.102050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '007b4e6be146'
down_revision: Union[str, None] = '9c4e7b2a1d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tg_topics',
    sa.Column('customer_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_tg_topics_customer_chat_id'), 'customer_tg_topics', ['customer_chat_id'], unique=True)
    op.create_index(op.f('ix_customer_tg_topics_topic_id'), 'customer_tg_topics', ['topic_id'], unique=True)
    op.drop_table('user_cities')
    op.drop_index(op.f('ix_airport_names_airport_id'), table_name='airport_names')
    op.drop_index(op.f('ix_airport_names_language_code'), table_name='airport_names')
    op.drop_index(op.f('ix_airport_names_language_name'), table_name='airport_names')
    op.drop_table('airport_names')
    op.drop_index(op.f('ix_airports_city_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_icao_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_ident'), table_name='airports')
    op.drop_table('airports')
    op.drop_column('cities', 'is_viewed')
    op.drop_column('countries', 'is_viewed')
    op.drop_column('requests', 'baggage_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('baggage_types', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('countries', sa.Column('is_viewed', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('is_viewed', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
    op.alter_column('requests', 'baggage_types', server_default=None)
    op.alter_column('countries', 'is_viewed', server_default=None)
    op.alter_column('cities', 'is_viewed', server_default=None)
    op.create_table('airports',
    sa.Column('ident', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('airport_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iata_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icao_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('scheduled_service', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('airports_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('airports_pkey'))
    )
    op.create_index(op.f('ix_airports_ident'), 'airports', ['ident'], unique=True)
    op.create_index(op.f('ix_airports_icao_code'), 'airports', ['icao_code'], unique=False)
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_city_id'), 'airports', ['city_id'], unique=False)
    op.create_table('airport_names',
    sa.Column('airport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], name=op.f('airport_names_airport_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('airport_names_pkey')),
    sa.UniqueConstraint('airport_id', 'language_code', 'name', name=op.f('uq_airport_names_entity_language_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_airport_names_language_name'), 'airport_names', ['language_code', 'name'], unique=False)
    op.create_index(op.f('ix_airport_names_language_code'), 'airport_names', ['language_code'], unique=False)
    op.create_index(op.f('ix_airport_names_airport_id'), 'airport_names', ['airport_id'], unique=False)
    op.create_table('user_cities',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('user_cities_city_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('user_cities_created_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_cities_pkey')),
    sa.UniqueConstraint('name', name=op.f('user_cities_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_customer_tg_topics_topic_id'), table_name='customer_tg_topics')
    op.drop_index(op.f('ix_customer_tg_topics_customer_chat_id'), table_name='customer_tg_topics')
    op.drop_table('customer_tg_topics')
    # ### end Alembic commands ###
