"""empty message

Revision ID: 2c205af61a9e
Revises: eabbe29047e9
Create Date: 2026-01-22 10:26:25.791447

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c205af61a9e"
down_revision: Union[str, None] = "eabbe29047e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("is_viewed", sa.Boolean(), nullable=False))
    op.add_column("countries", sa.Column("is_viewed", sa.Boolean(), nullable=False))

    # Use raw SQL to handle the type conversion with explicit USING clause
    # Convert VARCHAR to JSON - convert text to JSON string value
    # to_jsonb() will wrap plain text as a JSON string, which is then cast to JSON
    op.execute(
        """
        ALTER TABLE requests
        ALTER COLUMN baggage_types
        TYPE JSON USING to_jsonb(baggage_types::text)::json
    """
    )

    op.drop_column("requests", "notified_request_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "notified_request_ids",
            postgresql.ARRAY(sa.BIGINT()),
            server_default=sa.text("'{}'::bigint[]"),
            autoincrement=False,
            nullable=False,
        ),
    )

    # Use raw SQL to convert JSON back to VARCHAR
    op.execute(
        """
        ALTER TABLE requests
        ALTER COLUMN baggage_types
        TYPE VARCHAR USING baggage_types::text
    """
    )

    op.drop_column("countries", "is_viewed")
    op.drop_column("cities", "is_viewed")
    # ### end Alembic commands ###
