"""optional-city-id

Revision ID: 5a1e30bed57c
Revises: 956ac588043d
Create Date: 2024-07-12 22:21:19.732429

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a1e30bed57c"
down_revision: Union[str, None] = "956ac588043d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_cities", "city_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_cities", "city_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
