"""empty message

Revision ID: 7561ac255540
Revises: 007b4e6be146
Create Date: 2026-09-02 11:33:06.828337

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7561ac255540"
down_revision: Union[str, None] = "007b4e6be146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "comment", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "comment", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
