"""delete-created_by-country

Revision ID: 956ac588043d
Revises: 52eac5d9ca08
Create Date: 2024-07-12 22:18:31.928220

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "956ac588043d"
down_revision: Union[str, None] = "52eac5d9ca08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("countries_created_by_id_fkey", "countries", type_="foreignkey")
    op.drop_column("countries", "created_by_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries",
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "countries_created_by_id_fkey", "countries", "users", ["created_by_id"], ["id"]
    )
    # ### end Alembic commands ###
