"""sender requests

Revision ID: 9e836722a270
Revises: fd53604bfec3
Create Date: 2024-05-18 19:29:42.099982

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9e836722a270"
down_revision: Union[str, None] = "fd53604bfec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
