"""empty message

Revision ID: a29d88f3d720
Revises: aebce7cab383
Create Date: 2025-01-05 12:18:08.731228

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a29d88f3d720"
down_revision: Union[str, None] = "aebce7cab383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("origin_id", sa.Integer(), nullable=False))
    op.add_column("requests", sa.Column("dest_id", sa.Integer(), nullable=False))
    op.add_column("requests", sa.Column("date", sa.Date(), nullable=False))
    op.add_column("requests", sa.Column("baggage_types", sa.String(), nullable=False))
    op.add_column("requests", sa.Column("comment", sa.String(), nullable=False))
    op.create_foreign_key(None, "requests", "user_cities", ["dest_id"], ["id"])
    op.create_foreign_key(None, "requests", "user_cities", ["origin_id"], ["id"])
    op.drop_column("requests", "date_to")
    op.drop_column("requests", "baggage_kind")
    op.drop_column("requests", "origin")
    op.drop_column("requests", "date_from")
    op.drop_column("requests", "volume_kind")
    op.drop_column("requests", "destination")
    op.drop_column("requests", "volume")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column("volume", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "requests",
        sa.Column("destination", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "requests",
        sa.Column(
            "volume_kind",
            postgresql.ENUM("kilo", "liter", "piece", name="volumekind"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "requests",
        sa.Column("date_from", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "requests",
        sa.Column("origin", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "requests",
        sa.Column(
            "baggage_kind",
            postgresql.ENUM(
                "usual",
                "liquid",
                "expensive",
                "document",
                "troublesome",
                name="baggagekind",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "requests", sa.Column("date_to", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_column("requests", "comment")
    op.drop_column("requests", "baggage_types")
    op.drop_column("requests", "date")
    op.drop_column("requests", "dest_id")
    op.drop_column("requests", "origin_id")
    # ### end Alembic commands ###
