"""empty message

Revision ID: e86eca49b998
Revises: 98e141bbc3fb
Create Date: 2025-06-29 14:12:22.346338

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e86eca49b998"
down_revision: Union[str, None] = "98e141bbc3fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("date_to", sa.Date(), nullable=True))
    op.add_column("requests", sa.Column("date_from", sa.Date(), nullable=True))
    op.alter_column("requests", "date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "date", existing_type=sa.DATE(), nullable=False)
    op.drop_column("requests", "date_from")
    op.drop_column("requests", "date_to")
    # ### end Alembic commands ###
