"""notifay_about_request

Revision ID: eabbe29047e9
Revises: e86eca49b998
Create Date: 2025-12-07 21:00:23.301222

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eabbe29047e9"
down_revision: Union[str, None] = "e86eca49b998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "requests",
        sa.Column(
            "notified_request_ids",
            postgresql.ARRAY(sa.BigInteger()),
            nullable=False,
            server_default="{}",  # пустой массив как default
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "notified_request_ids")
    # ### end Alembic commands ###
